version: '3'

services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    environment:
      DB_URL: 'mongodb://db:27017/test'

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
  
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes: 
      - test:/data/db

volumes:
  test: 
