name: Run Jest Tests on Pre-Push

on:
  push:
    branches:
      - main # Change this to your main branch name if it's different

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
    
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
    
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
    
      - name: Run tests
        run: npm test
        working-directory: ./frontend