name: Run Jest Tests on Pre-Push

on:
  push:
    branches:
      - main # Change this to your main branch name if it's different

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Navigate to Subfolder
        run: cd frontend # Replace 'frontend' with your subfolder name

      - name: Install dependencies
        run: npm install

      - name: Run Jest Tests
        run: npm test
